DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

breeds/urls.py
from django.conf.urls import url
from breeds import views

urlpatterns = [
    url(r'^breeds$', views.breeds, name='breeds_home'),
    url(r'^breeds/list$', views.list, name='breeds_list'),
    url(r'^breeds/list/(?P<pk>\d+)$', views.breed, name='breeds_breed'),
    url(r'^breeds/breeds_manage_list$', views.breeds_manage_list, name='breeds_manage_list'),
    url(r'^breeds/breeds_manage/(?P<pk>\d+)$', views.breeds_manage_detail, name='breeds_manage_detail'),
    url(r'^breeds/breeds_manage/create$', views.breeds_manage_create, name='breeds_manage_create'),
    url(r'^breeds/breeds_manage/update/(?P<pk>\d+)$', views.breeds_manage_update, name='breeds_manage_update'),
    url(r'^breeds/breeds_manage/delete/(?P<pk>\d+)$', views.breeds_manage_delete, name='breeds_manage_delete'),
    url(r'^breeds/distribution$', views.distribution, name='breeds_distribution'),
    url(r'^breeds/distribution/(?P<pk>[A-Z][A-Z])', views.country_region, name='breeds_country_region'),
    url(r'^breeds/video$', views.video, name='breeds_video'),
    url(r'^breeds/album$', views.BreedsAlbumView.as_view(), name='breeds_album'),
]

oauth2_provider/urls.py
from __future__ import absolute_import

from django.conf.urls import url

from . import views


app_name = 'oauth2_provider'


base_urlpatterns = [
    url(r'^authorize/$', views.AuthorizationView.as_view(), name="authorize"),
    url(r'^token/$', views.TokenView.as_view(), name="token"),
    url(r'^revoke_token/$', views.RevokeTokenView.as_view(), name="revoke-token"),
]


management_urlpatterns = [
    # Application management views
    url(r'^applications/$', views.ApplicationList.as_view(), name="list"),
    url(r'^applications/register/$', views.ApplicationRegistration.as_view(), name="register"),
    url(r'^applications/(?P<pk>[\w-]+)/$', views.ApplicationDetail.as_view(), name="detail"),
    url(r'^applications/(?P<pk>[\w-]+)/delete/$', views.ApplicationDelete.as_view(), name="delete"),
    url(r'^applications/(?P<pk>[\w-]+)/update/$', views.ApplicationUpdate.as_view(), name="update"),
    # Token management views
    url(r'^authorized_tokens/$', views.AuthorizedTokensListView.as_view(), name="authorized-token-list"),
    url(r'^authorized_tokens/(?P<pk>[\w-]+)/delete/$', views.AuthorizedTokenDeleteView.as_view(),
        name="authorized-token-delete"),
]


urlpatterns = base_urlpatterns + management_urlpatterns

oauth2_provider/forms.py
from django import forms


class AllowForm(forms.Form):
    allow = forms.BooleanField(required=False)
    redirect_uri = forms.CharField(widget=forms.HiddenInput())
    scope = forms.CharField(widget=forms.HiddenInput())
    client_id = forms.CharField(widget=forms.HiddenInput())
    state = forms.CharField(required=False, widget=forms.HiddenInput())
    response_type = forms.CharField(widget=forms.HiddenInput())

oauth2_provider/views/application.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import Textarea
from django.forms.models import modelform_factory
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView

from ..models import get_application_model


class ApplicationOwnerIsUserMixin(LoginRequiredMixin):
    """
    This mixin is used to provide an Application queryset filtered by the current request.user.
    """
    fields = '__all__'

    def get_queryset(self):
        return get_application_model().objects.filter(user=self.request.user)


class ApplicationRegistration(LoginRequiredMixin, CreateView):
    """
    View used to register a new Application for the request.user
    """
    template_name = "oauth2_provider/application_registration_form.html"

    def get_form_class(self):
        """
        Returns the form class for the application model
        """
        return modelform_factory(
            get_application_model(),
            fields=('name', 'client_id', 'client_secret', 'client_type',
                    'authorization_grant_type', 'redirect_uris'),
            widgets = {
                'client_secret': Textarea(attrs={'cols': 80, 'rows': 2}),
                'redirect_uris': Textarea(attrs={'cols': 80, 'rows': 2}),
            }

        )

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ApplicationRegistration, self).form_valid(form)


class ApplicationDetail(ApplicationOwnerIsUserMixin, DetailView):
    """
    Detail view for an application instance owned by the request.user
    """
    context_object_name = 'application'
    template_name = "oauth2_provider/application_detail.html"


class ApplicationList(ApplicationOwnerIsUserMixin, ListView):
    """
    List view for all the applications owned by the request.user
    """
    context_object_name = 'applications'
    template_name = "oauth2_provider/application_list.html"


class ApplicationDelete(ApplicationOwnerIsUserMixin, DeleteView):
    """
    View used to delete an application owned by the request.user
    """
    context_object_name = 'application'
    success_url = reverse_lazy('oauth2_provider:list')
    template_name = "oauth2_provider/application_confirm_delete.html"


class ApplicationUpdate(ApplicationOwnerIsUserMixin, UpdateView):
    """
    View used to update an application owned by the request.user
    """
    context_object_name = 'application'
    template_name = "oauth2_provider/application_form.html"

    def get_form_class(self):
        """
        Returns the form class for the application model
        """
        return modelform_factory(
            get_application_model(),
            fields=('name', 'client_id', 'client_secret', 'client_type',
                    'authorization_grant_type', 'redirect_uris'),
            widgets={
                'client_secret': Textarea(attrs={'cols': 80, 'rows': 2}),
                'redirect_uris': Textarea(attrs={'cols': 80, 'rows': 2}),
            }
        )

oauth2_provider/views/base.py
import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView, View

from .mixins import OAuthLibMixin
from ..exceptions import OAuthToolkitError
from ..forms import AllowForm
from ..http import HttpResponseUriRedirect
from ..models import get_application_model
from ..scopes import get_scopes_backend
from ..settings import oauth2_settings


log = logging.getLogger('oauth2_provider')


class BaseAuthorizationView(LoginRequiredMixin, OAuthLibMixin, View):
    """
    Implements a generic endpoint to handle *Authorization Requests* as in :rfc:`4.1.1`. The view
    does not implement any strategy to determine *authorize/do not authorize* logic.
    The endpoint is used in the following flows:

    * Authorization code
    * Implicit grant

    """
    def dispatch(self, request, *args, **kwargs):
        self.oauth2_data = {}
        return super(BaseAuthorizationView, self).dispatch(request, *args, **kwargs)

    def error_response(self, error, **kwargs):
        """
        Handle errors either by redirecting to redirect_uri with a json in the body containing
        error details or providing an error response
        """
        redirect, error_response = super(BaseAuthorizationView, self).error_response(error, **kwargs)

        if redirect:
            return HttpResponseUriRedirect(error_response['url'])

        status = error_response['error'].status_code
        return self.render_to_response(error_response, status=status)


class AuthorizationView(BaseAuthorizationView, FormView):
    """
    Implements an endpoint to handle *Authorization Requests* as in :rfc:`4.1.1` and prompting the
    user with a form to determine if she authorizes the client application to access her data.
    This endpoint is reached two times during the authorization process:
    * first receive a ``GET`` request from user asking authorization for a certain client
    application, a form is served possibly showing some useful info and prompting for
    *authorize/do not authorize*.

    * then receive a ``POST`` request possibly after user authorized the access

    Some informations contained in the ``GET`` request and needed to create a Grant token during
    the ``POST`` request would be lost between the two steps above, so they are temporarily stored in
    hidden fields on the form.
    A possible alternative could be keeping such informations in the session.

    The endpoint is used in the following flows:
    * Authorization code
    * Implicit grant
    """
    template_name = 'oauth2_provider/authorize.html'
    form_class = AllowForm

    server_class = oauth2_settings.OAUTH2_SERVER_CLASS
    validator_class = oauth2_settings.OAUTH2_VALIDATOR_CLASS
    oauthlib_backend_class = oauth2_settings.OAUTH2_BACKEND_CLASS

    skip_authorization_completely = False

    def get_initial(self):
        # TODO: move this scopes conversion from and to string into a utils function
        scopes = self.oauth2_data.get('scope', self.oauth2_data.get('scopes', []))
        initial_data = {
            'redirect_uri': self.oauth2_data.get('redirect_uri', None),
            'scope': ' '.join(scopes),
            'client_id': self.oauth2_data.get('client_id', None),
            'state': self.oauth2_data.get('state', None),
            'response_type': self.oauth2_data.get('response_type', None),
        }
        return initial_data

    def form_valid(self, form):
        try:
            credentials = {
                'client_id': form.cleaned_data.get('client_id'),
                'redirect_uri': form.cleaned_data.get('redirect_uri'),
                'response_type': form.cleaned_data.get('response_type', None),
                'state': form.cleaned_data.get('state', None),
            }

            scopes = form.cleaned_data.get('scope')
            allow = form.cleaned_data.get('allow')
            uri, headers, body, status = self.create_authorization_response(
                request=self.request, scopes=scopes, credentials=credentials, allow=allow)
            self.success_url = uri
            log.debug("Success url for the request: {0}".format(self.success_url))
            return HttpResponseUriRedirect(self.success_url)

        except OAuthToolkitError as error:
            return self.error_response(error)

    def get(self, request, *args, **kwargs):
        try:
            scopes, credentials = self.validate_authorization_request(request)
            all_scopes = get_scopes_backend().get_all_scopes()
            kwargs["scopes_descriptions"] = [all_scopes[scope] for scope in scopes]
            kwargs['scopes'] = scopes
            # at this point we know an Application instance with such client_id exists in the database

            # TODO: Cache this!
            application = get_application_model().objects.get(client_id=credentials["client_id"])

            kwargs['application'] = application
            kwargs['client_id'] = credentials['client_id']
            kwargs['redirect_uri'] = credentials['redirect_uri']
            kwargs['response_type'] = credentials['response_type']
            kwargs['state'] = credentials['state']

            self.oauth2_data = kwargs
            # following two loc are here only because of https://code.djangoproject.com/ticket/17795
            form = self.get_form(self.get_form_class())
            kwargs['form'] = form

            # Check to see if the user has already granted access and return
            # a successful response depending on 'approval_prompt' url parameter
            require_approval = request.GET.get('approval_prompt', oauth2_settings.REQUEST_APPROVAL_PROMPT)

            # If skip_authorization field is True, skip the authorization screen even
            # if this is the first use of the application and there was no previous authorization.
            # This is useful for in-house applications-> assume an in-house applications
            # are already approved.
            if application.skip_authorization:
                uri, headers, body, status = self.create_authorization_response(
                    request=self.request, scopes=" ".join(scopes),
                    credentials=credentials, allow=True)
                return HttpResponseUriRedirect(uri)

            elif require_approval == 'auto':
                tokens = request.user.accesstoken_set.filter(application=kwargs['application'],
                                                             expires__gt=timezone.now()).all()
                # check past authorizations regarded the same scopes as the current one
                for token in tokens:
                    if token.allow_scopes(scopes):
                        uri, headers, body, status = self.create_authorization_response(
                            request=self.request, scopes=" ".join(scopes),
                            credentials=credentials, allow=True)
                        return HttpResponseUriRedirect(uri)

            return self.render_to_response(self.get_context_data(**kwargs))

        except OAuthToolkitError as error:
            return self.error_response(error)


@method_decorator(csrf_exempt, name="dispatch")
class TokenView(OAuthLibMixin, View):
    """
    Implements an endpoint to provide access tokens

    The endpoint is used in the following flows:
    * Authorization code
    * Password
    * Client credentials
    """
    server_class = oauth2_settings.OAUTH2_SERVER_CLASS
    validator_class = oauth2_settings.OAUTH2_VALIDATOR_CLASS
    oauthlib_backend_class = oauth2_settings.OAUTH2_BACKEND_CLASS

    @method_decorator(sensitive_post_parameters('password'))
    def post(self, request, *args, **kwargs):
        url, headers, body, status = self.create_token_response(request)
        response = HttpResponse(content=body, status=status)

        for k, v in headers.items():
            response[k] = v
        return response


@method_decorator(csrf_exempt, name="dispatch")
class RevokeTokenView(OAuthLibMixin, View):
    """
    Implements an endpoint to revoke access or refresh tokens
    """
    server_class = oauth2_settings.OAUTH2_SERVER_CLASS
    validator_class = oauth2_settings.OAUTH2_VALIDATOR_CLASS
    oauthlib_backend_class = oauth2_settings.OAUTH2_BACKEND_CLASS

    def post(self, request, *args, **kwargs):
        url, headers, body, status = self.create_revocation_response(request)
        response = HttpResponse(content=body or '', status=status)

        for k, v in headers.items():
            response[k] = v
        return response

oauth2_provider/views/generic.py
from django.views.generic import View

from .mixins import ProtectedResourceMixin, ReadWriteScopedResourceMixin, ScopedResourceMixin
from ..settings import oauth2_settings


class ProtectedResourceView(ProtectedResourceMixin, View):
    """
    Generic view protecting resources by providing OAuth2 authentication out of the box
    """
    server_class = oauth2_settings.OAUTH2_SERVER_CLASS
    validator_class = oauth2_settings.OAUTH2_VALIDATOR_CLASS
    oauthlib_backend_class = oauth2_settings.OAUTH2_BACKEND_CLASS


class ScopedProtectedResourceView(ScopedResourceMixin, ProtectedResourceView):
    """
    Generic view protecting resources by providing OAuth2 authentication and Scopes handling
    out of the box
    """
    pass


class ReadWriteScopedResourceView(ReadWriteScopedResourceMixin, ProtectedResourceView):
    """
    Generic view protecting resources with OAuth2 authentication and read/write scopes.
    GET, HEAD, OPTIONS http methods require "read" scope. Otherwise "write" scope is required.
    """
    pass

oauth2_provider/views/token.py
from __future__ import absolute_import, unicode_literals

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DeleteView, ListView

from ..models import AccessToken


class AuthorizedTokensListView(LoginRequiredMixin, ListView):
    """
    Show a page where the current logged-in user can see his tokens so they can revoke them
    """
    context_object_name = 'authorized_tokens'
    template_name = 'oauth2_provider/authorized-tokens.html'
    model = AccessToken

    def get_queryset(self):
        """
        Show only user's tokens
        """
        return super(AuthorizedTokensListView, self).get_queryset()\
            .select_related('application').filter(user=self.request.user)


class AuthorizedTokenDeleteView(LoginRequiredMixin, DeleteView):
    """
    View for revoking a specific token
    """
    template_name = 'oauth2_provider/authorized-token-delete.html'
    success_url = reverse_lazy('oauth2_provider:authorized-token-list')
    model = AccessToken

    def get_queryset(self):
        return super(AuthorizedTokenDeleteView, self).get_queryset().filter(user=self.request.user)

oauth2_provider/templates/oauth2_provider/application_confirm_delete.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}
{% block inner-content %}
    <div class="block-center">
        <h3 class="block-center-heading">{% trans "Are you sure to delete the application" %} {{ application.name }}?</h3>
        <form method="post" action="{% url 'oauth2_provider:delete' application.pk %}">
            {% csrf_token %}

            <div class="control-group">
                <div class="controls">
                    <a class="btn btn-large" href="{% url "oauth2_provider:list" %}">{% trans "Cancel" %}</a>
                    <input type="submit" class="btn btn-large btn-danger" name="allow" value="{% trans "Delete" %}"/>
                </div>
            </div>
        </form>
    </div>
{% endblock inner-content %}

oauth2_provider/templates/oauth2_provider/application_detail.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}
{% block inner-content %}
    <div>
        <h3 class="block-center-heading">{{ application.name }}</h3>

        <ul>
            <li>
                <div><b>{% trans "Client id" %}</b></div>
                <div>{{ application.client_id }}</div>
                <br/>
            </li>

            <li>
                <div><b>{% trans "Client secret" %}</b></div>
                <div class="wrap-string">{{ application.client_secret }}</div>
                <br/>
            </li>

            <li>
                <div><b>{% trans "Client type" %}</b></div>
                <div>{{ application.client_type }}</div>
                <br/>
            </li>

            <li>
                <div><b>{% trans "Authorization Grant Type" %}</b></div>
                <div>{{ application.authorization_grant_type }}</div>
                <br/>
            </li>

            <li>
                <div><b>{% trans "Redirect Uris" %}</b></div>
                <div class="wrap-string">{{ application.redirect_uris }}</div>
                <br/>
            </li>
        </ul>

        <div class="btn-toolbar">
            <a class="btn" href="{% url "oauth2_provider:list" %}">{% trans "Go Back" %}</a>
            <a class="btn btn-primary" href="{% url "oauth2_provider:update" application.id %}">{% trans "Edit" %}</a>
            <a class="btn btn-danger" href="{% url "oauth2_provider:delete" application.id %}">{% trans "Delete" %}</a>
        </div>
    </div>
{% endblock inner-content %}

oauth2_provider/templates/oauth2_provider/application_form.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}
{% load bootstrap3 %}

{% block inner-content %}
    <div class="block-center">
        <form method="post" action="

                {% block app-form-action-url %}{% url 'oauth2_provider:update' application.id %}{% endblock app-form-action-url %}">
            <h3 class="block-center-heading">
                {% block app-form-title %}
                    {% trans "Edit application" %} {{ application.name }}
                {% endblock app-form-title %}
            </h3>
            {% csrf_token %}
            {% bootstrap_form form %}

            <div class="control-group {% if form.non_field_errors %}error{% endif %}">
                {% for error in form.non_field_errors %}
                    <span class="help-inline">{{ error }}</span>
                {% endfor %}
            </div>

            <div class="control-group">
                <div class="controls">
                    <a class="btn" href="

                            {% block app-form-back-url %}{% url "oauth2_provider:detail" application.id %}{% endblock app-form-back-url %}">
                        {% trans "Go Back" %}
                    </a>
                    <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

oauth2_provider/templates/oauth2_provider/application_list.html
{% extends "oauth2_provider/base.html" %}
{% load i18n %}

{% block title %}{% trans "Your applications" %}{% endblock %}

{% block inner-content %}
    <h1>{% trans "Your applications" %}</h1>
    <hr>
    <div class="block-center">
        {% if applications %}
            <ul>
                {% for application in applications %}
                    <li><a href="{{ application.get_absolute_url }}">{{ application.name }}</a></li>
                {% endfor %}
            </ul>

            <a class="btn btn-success" href="{% url "oauth2_provider:register" %}">{% trans "New Application" %}</a>
        {% else %}
            <p>{% trans "No applications defined" %}. <a
                    href="{% url 'oauth2_provider:register' %}">{% trans "Click here" %}</a> {% trans "if you want to register a new one" %}
            </p>
        {% endif %}
    </div>
{% endblock inner-content %}

oauth2_provider/templates/oauth2_provider/application_registration_form.html
{% extends "oauth2_provider/application_form.html" %}

{% load i18n %}

{% block app-form-title %}{% trans "Register a new application" %}{% endblock app-form-title %}

{% block app-form-action-url %}{% url 'oauth2_provider:register' %}{% endblock app-form-action-url %}

{% block app-form-back-url %}{% url "oauth2_provider:list" %}"{% endblock app-form-back-url %}

oauth2_provider/templates/oauth2_provider/authorize.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}
{% block inner-content %}
    <div class="block-center">
        {% if not error %}
            <form id="authorizationForm" method="post">
                <h3 class="block-center-heading">{% trans "Authorize" %} {{ application.name }}?</h3>
                {% csrf_token %}

                {% for field in form %}
                    {% if field.is_hidden %}
                        {{ field }}
                    {% endif %}
                {% endfor %}

                <p>{% trans "Application requires following permissions" %}</p>
                <ul>
                    {% for scope in scopes_descriptions %}
                        <li>{{ scope }}</li>
                    {% endfor %}
                </ul>

                {{ form.errors }}
                {{ form.non_field_errors }}

                <div class="control-group">
                    <div class="controls">
                        <input type="submit" class="btn btn-large" value={% trans "Cancel" %}>
                        <input type="submit" class="btn btn-large btn-primary" name="allow" value={% trans "Authorize" %}>
                    </div>
                </div>
            </form>

        {% else %}
            <h2>{% trans "Error:" %} {{ error.error }}</h2>
            <p>{{ error.description }}</p>
        {% endif %}
    </div>
{% endblock %}

oauth2_provider/templates/oauth2_provider/authorized-token-delete.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}
{% block inner-content %}
    <form action="" method="post">{% csrf_token %}
        <p>{% trans "Are you sure you want to delete this token?" %}</p>
        <input type="submit" value="{% trans "Delete" %}" />
    </form>
{% endblock %}

oauth2_provider/templates/oauth2_provider/authorized-tokens.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}
{% block inner-content %}
    <div class="block-center">
    <h1>{% trans "Tokens" %}</h1>
        <ul>
        {% for authorized_token in authorized_tokens %}
            <li>
                {{ authorized_token.application }}
                (<a href="{% url 'oauth2_provider:authorized-token-delete' authorized_token.pk %}">{% trans "Revoke" %}</a>)
            </li>
            <ul>
            {% for scope_name, scope_description in authorized_token.scopes.items %}
                <li>{{ scope_name }}: {{ scope_description }}</li>
            {% endfor %}
            </ul>
        {% empty %}
            <li>{% trans "There are no authorized tokens yet." %}</li>
        {% endfor %}
        </ul>
    </div>
{% endblock %}

oauth2_provider/templates/oauth2_provider/base.html
{% extends "bootstrap/bootstrap.html" %}
{% load i18n %}
{% load bootstrap3 %}

{% block head_title %}{% trans "Application" %}{% endblock %}

oauth2_provider/templates/oauth2_provider/base_original.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    {% block css %}
        <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
    {% endblock css %}

    <style>
        body {
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }
        .block-center {
            max-width: 500px;
            padding: 19px 29px 29px;
            margin: 0 auto 20px;
            background-color: #fff;
            border: 1px solid #e5e5e5;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
            -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
            -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
            box-shadow: 0 1px 2px rgba(0,0,0,.05);
        }
        .block-center .block-center-heading {
            margin-bottom: 10px;
        }

    </style>
</head>

<body>

<div class="container">
    {% block content %}
    {% endblock content %}
</div>

</body>
</html>